# Generated by Django 4.0.5 on 2022-09-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=80)),
                ('mobile_no', models.CharField(default='', max_length=20)),
                ('city', models.CharField(max_length=60)),
                ('location', models.CharField(default='', max_length=100)),
                ('ip_address', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
