# Generated by Django 4.0.5 on 2022-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0004_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_token',
            field=models.CharField(default='_', max_length=200),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
