# Generated by Django 3.2.7 on 2022-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0005_remove_logindata_is_verified_userdata_email_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
