# Generated by Django 3.2.7 on 2022-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0006_auto_20220917_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='u_no',
            field=models.CharField(default='', max_length=20),
        ),
    ]
