# Generated by Django 3.2.7 on 2022-09-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0007_logindata_u_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindata',
            name='u_no',
            field=models.CharField(default='', max_length=40),
        ),
    ]
