# Generated by Django 3.2.7 on 2022-09-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0008_alter_logindata_u_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('u_no', models.CharField(max_length=50)),
            ],
        ),
    ]
