# Generated by Django 3.2.7 on 2022-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0010_forget_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_id', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='Please specify Category', max_length=50)),
                ('short_desc', models.CharField(default='Please specify desc', max_length=200)),
                ('desc', models.CharField(max_length=5000)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='events/images')),
                ('status', models.CharField(default='Specify Status', max_length=50)),
                ('pub_date', models.DateField()),
                ('slug', models.CharField(default='/', max_length=200)),
                ('page_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
