# Generated by Django 3.2.7 on 2022-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0011_maindata_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='image',
            field=models.ImageField(default='', upload_to='product/images'),
        ),
    ]
