# Generated by Django 3.2.7 on 2022-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0014_headcarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='no',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
