# Generated by Django 3.2.7 on 2022-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0015_customerreview_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='class1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
