# Generated by Django 3.2.7 on 2022-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0016_customerreview_class1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='class1',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
