# Generated by Django 3.2.7 on 2022-09-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullhad', '0017_alter_customerreview_class1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
